server:
  port: 9559
  servlet:
    context-path: /conf
spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/public/,classpath:/static/
eureka:
 client:
  service-url:
   defaultZone: http://localhost:6868/eureka
 instance:
   prefer-ip-address: true