#服务
server:
  port: 8080
  servlet:
    context-path: /
#    context-path: /

# 日志配置   默认配置ERROR、WARN和INFO级别的日志输出到控制台。
debug: true
# 日志配置
logging:
#  file: log/AhutOne.log
#  path: /web/target/log
  level:
    # com.ahut包下所有class以DEBUG级别输出
    com.wang: DEBUG
    # root日志以WARN级别输出
    root: WARN
  config: classpath:logback-spring.xml

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mybatis配置文件
    config-location: classpath:/conf/mybatis-config.xml
  # 映射文件所在路径com.wang.mapperweb/
  mapper-locations: classpath:/mapper/*
  # 前面的 - 不要删除

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



people:
  name: wang
  password: 123

spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    deserialization:
#      #允许对象忽略json中不存在的属性
#      fail_on_unknown_properties: false
#    serialization:
#
#      #格式化输出
#      indent_output: true
#      #忽略无法转换的对象
#      fail_on_empty_beans: false
#    #设置空如何序列化 NON_DEFAULT  NON_EMPTY   NON_NULL
#    default-property-inclusion: NON_EMPTY
#    parser:
#          #允许出现特殊字符和转义符
#          allow_unquoted_control_chars: true
#          #允许出现单引号
#          allow_single_quotes: true


  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  mvc:
    view:
      prefix: /
      suffix: .html
  freemarker:
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    suffix: .html
    template-loader-path: classpath:/template/
  resources:
    static-locations: classpath:/template/
#    static-locations: classpath:/public/,classpath:/template/
  cache:
    ehcache:
      config: classpath:ehcache.xml
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: admin
    password: admin
  data:
    solr:
      host: http://192.168.1.44:8983/solr/new_core