server:
  port: 9001
#  servlet:
#    context-path: /flower

spring:
  application:
    name: flower-base #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flower_base?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
#  rabbitmq:
#    host: 192.168.99.100
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          format_sql: true
eureka:
 client:
  service-url:
    defaultZone: http://localhost:6868/eureka/
 instance:
   prefer-ip-address: true
#ribbon:
#  eureka:
#    enabled: true