server:
  port: 12000
spring:
  application:
  name: flower-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wangxt59/flower-config.git
          username: wangxt59
          password: wxt199559
  rabbitmq:
    host: 192.168.99.100
    username: admin
    password: admin
  devtools:
    add-properties: false


management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

