server: 
  port: 9009
spring: 
  application:  
    name: flower-friend #指定服务名
  datasource:  
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flower_friend?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          format_sql: true
  redis:
    host: 192.168.99.100

eureka:
 client:
  service-url:
   defaultZone: http://localhost:6868/eureka
 instance:
   prefer-ip-address: true

jwt:
  config:
    key: itcast