server: 
  port: 9001
spring:
  application:  
    name: flower_article #指定服务名
  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/flower_article?characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: root

  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          format_sql: true
  redis:
    host: 192.168.99.100
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      database: spitdb
eureka:
 client:
  service-url:
   defaultZone: http://localhost:6868/eureka
 instance:
   prefer-ip-address: true
